### ISSUE TITLE
First batch of inital problems

### ISSUE THREAD

**Issue by allakatter** [k3larra/commuter#2]
Here are some of the things i want to point out from using the app for the first time. 

 
**Functionality**
- The "search for stop" button does not work from the "undervisning" page.
- The "undervisning" page does not work from the "search for stop" page.
- The "settings" text is greyed out from the "search for stop" page. 
- The app sometimes resets my "from" and "to" bars to the previously selected destinations when i put the app in the background and then again to the foreground. 
- The "Back" button on my phone seems to sometimes reset the "Waiting on GPU location" pop up.

**Design**
 
 I understand that the app is mainly for exploring the possibilities of machine learning, there is however nothing wrong with making the user experience better.

- The text on the left that indicates time on the "main" page would be less of a struggle to read if the last number was on the same horizontal line as the rest. This could be achieved by either making the time icons on the left a bit smaller, or reducing the text seize. 
- There is no indication from which platform the train is departing from, this seems like a necessary feature to have in a travel app.
- Rather than using the "back" button on the phone all the time, a dedicated "home" page or some such would feel a lot better than just relying on the "back" button all the time. 
- The "Går om:" text needs a space in between the "Hours" and "Minutes" information. Just now it looks like this "**Går om:** 12 timmar34minuter" when it should correctly look like this **""Går om:** 12 timmar 34 minuter" 
- The "**Byte:**" text is a bit unclear. an example would be "**Byte:** 2 the first to+ 126, Löddeköpinge Center Syd". I don't really understand what the "2" indicates, and neither the "+".

**Comment by k3larra** [comment]
Dear All Cats
Thank you so much for the input, comments and planned actions can be found below:

* _Regarding Functionality 1-3_ : this is about navigation and it is a patch-work :| . I will do some homework and read the Android design Guidelines on navigation. All input on a prefered navigation structure is welcome.
* _Regarding Functionality 4-5_ : Could you please provide a description on how I can reproduce the problems. (Phone brand, model, screen size and Android version could also be valuable input.)

* _Regarding Design 1_ :  Is it here where I use a center align where you would prefer a bottom align? Or is it that your screen size makes a line brake????
 
![Skärmklipp](https://user-images.githubusercontent.com/477262/55462511-37070200-55f7-11e9-9f6a-2e6b8d2a6582.PNG)

* ~_Regarding Design 2:_ I was about to say that that information is not in Skånetrafiken API... But now I checked and they actually added it since the XML parser was written. I will put it on the ToDo list.~
Done or added when a list item is expanded after "From XXX : Track
Has to be tested so it works IRL and then perhaps added someplace else....
![track](https://user-images.githubusercontent.com/477262/55486910-6c2e4700-562d-11e9-9026-1e51695a381a.PNG)

* _Regarding design 3:_ See functionality 1-3
* ~_Regarding design 4:_ Will fix~ _In version 45 also added fix for 1 hour......_
* ~_Regarding design 5:_ Will look into this.. not much space here.. 2 means that there will be two change of transport during the journey.~
_Made some changes here so it hopefully is clearer: two examples_
![One](https://user-images.githubusercontent.com/477262/55479475-739a2400-561e-11e9-80a1-87d105f77f24.PNG)
![Two](https://user-images.githubusercontent.com/477262/55479479-76951480-561e-11e9-9b4f-e0f024820601.PNG)
 

Thanks and some clarifications on design 1 and functionality 4 and 5 would be appreciated.
Regards
/L

**Comment by k3larra** [comment]
Fixed the items indicated above. Moved the remaining to other issues.
Updated the app on App store to version 44.

**Comment by allakatter** [comment]
Hi again Lars!
Here are some clarifications on functionality 4 & 5, as well as design 1. 

- _Regarding Functionality 4 - 5_: Select a destination, then tab out of the app, then tab in (It should now display the copper color), then swap your destination with where you are going from using the "swap" button, now tab in and out again. This will "reset" the two locations to what it previously was. The link below is a picture visualizing this procedure: 
https://imgur.com/a/Q6DtJEu

The "back" button resetting the ""Waiting on GPU location" pop up seems to have fixed itself, and i can no longer (for better or worse) reproduce the problem. 

- _Regarding Design 1_ 
Here is how i view it on my phone: 
https://imgur.com/a/GKyqvWE

I am using a Samsung Galaxy S9+, 15.75 cm Screen seize, running on Android version 8.0.

**Comment by k3larra** [comment]
This is the default behaviour or? The predictions swaps it back......
